name: iOS Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Установка Ruby 3.2 (чтобы избежать багов со старой версией)
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      # 3. Установка последней версии CocoaPods
      - name: Install latest CocoaPods
        run: |
          sudo gem install cocoapods --pre
          pod --version

      # 4. Cache для Pods (ускоряет CI)
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Validate Podfile
        run: cat Podfile


      # 5. Установка зависимостей через CocoaPods
      - name: Install Pods
        run: pod install

      # 6. Проверяем наличие схемы и workspace
      - name: Validate Xcode Workspace
        run: |
          ls -R dummy
          if [ ! -d "dummy/dummy.xcworkspace" ]; then
            echo "❌ Workspace not found! Did you share the scheme?"
            exit 1
          fi

      # 7. Запуск тестов
      - name: Run Tests
        run: |
          xcodebuild \
            -workspace dummy/dummy.xcworkspace \
            -scheme dummy \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
            clean test | xcpretty